import { twMerge } from "tailwind-merge";

/**
 * Utility to merge class names and dedupe Tailwind classes.
 * Mirrors the implementation generated by shadcn/ui template.
 */
export function cn(...inputs: any[]) {
  return twMerge(inputs.filter(Boolean).join(" "));
}
